# -*- coding: utf-8 -*-
"""Untitled38.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14X2BZkaVoyjT7PR3LEnD7nKrFMolwrn9
"""

!pip install diagrams

# diagram.py
from diagrams import Diagram
from diagrams.aws.compute import EC2
from diagrams.aws.database import RDS
from diagrams.aws.network import ELB

# Set the output path
output_path = "/content/web_service_diagram"

with Diagram("Web Service", show=False, filename=output_path, outformat="png"):
    ELB("lb") >> EC2("web") >> RDS("userdb")

print(f"Diagram saved at {output_path}.png")

from diagrams import Diagram
from diagrams.aws.storage import S3
from diagrams.custom import Custom

# Define the output path
output_path = "/content/Images/data_extraction_diagram"

with Diagram("Data Extraction Workflow", show=False, filename=output_path, outformat="png"):
    # S3 Bucket
    s3_bucket = S3("S3 Bucket")

    # Streamlit
    streamlit = Custom("Streamlit", "/content/Streamlit.png")
    streamlit_output = Custom("Streamlit Output", "/content/Streamlit.png")

    # PDF Processing - Open Source (PyMuPDF)
    pymupdf = Custom("PyMuPDF", "/content/pymupdf.png")
    pdf_image1 = Custom("PDF Image", "/content/pdf.png")
    pdf_image1 >> streamlit >> pymupdf

    # PDF Processing - Enterprise (Adobe API Extract)
    adobe_api = Custom("Adobe API Extract", "/content/adobe.png")
    pdf_image2 = Custom("PDF Image", "/content/pdf.png")
    pdf_image2 >> streamlit >> adobe_api

    # Website Scraping - Open Source (BeautifulSoup)
    beautiful_soup = Custom("BeautifulSoup", "/content/beautiful_soup.png")
    website_image1 = Custom("Website", "/content/website.png")
    website_image1 >> streamlit >> beautiful_soup

    # Website Scraping - Enterprise (Apify)
    apify = Custom("Apify", "/content/apify.png")
    website_image2 = Custom("Website", "/content/website.png")
    website_image2 >> streamlit >> apify

    # FastAPI
    fastapi = Custom("FastAPI", "/content/fastapi.png")
    pymupdf >> fastapi
    adobe_api >> fastapi
    beautiful_soup >> fastapi
    apify >> fastapi

    # FastAPI to S3
    fastapi >> s3_bucket

    # S3 Bucket Connections
    s3_bucket >> streamlit_output
    s3_bucket >> Custom("Render Cloud", "/content/render.png")

    # Streamlit Output Connections
    Custom("Render Cloud", "/content/render.png") >> streamlit_output
    streamlit_output >> s3_bucket

print(f"Diagram saved at {output_path}.png")

from google.colab import drive
drive.mount('/content/drive')

